import "@/sass/main.scss";

import type { Metadata } from "next";
//import { Header } from "./layout/Header";
import { Footer } from "./layout/Footer";
import { Main } from "./layout/Main";

export const metadata: Metadata = {
	title: "Paulo Wells' homepage",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{/* <Header /> */}
				<Main>
					{children}
				</Main>
				<Footer />
			</body>
		</html>
	);
}
